### ISSUE TITLE
[FEAT] 사용자 회원가입 기능을 구현한다.

### ISSUE THREAD

**Issue by Jin409** [Jin409/wanted-pre-onboarding-backend#4]
## ✅ 구현할 기능
- 사용자 회원가입 기능을 구현한다.

## 📝 TODO
- [x] 이메일과 비밀번호로 회원가입을 한다.
- [x] 이메일과 비밀번호에 대한 유효성 검사를 한다.
   - [x] 이메일 조건 : @ 포함
   - [x] 비밀번호 조건 : 8자 이상
   - [x] 추가적인 유효성 검사 조건은 포함하지 않는다.
- [x] 비밀번호는 암호화하여 저장한다.
